---
usgo_container_agagd_version: 'latest'
usgo_container_agagd_virtual_host: ''
usgo_container_agagd_letsencrypt_host: ''
usgo_container_agagd_db_host: ''
usgo_container_agagd_db_port: ''
usgo_container_agagd_db_name: ''
usgo_container_agagd_db_user: ''
usgo_container_agagd_db_password: ''
usgo_container_agagd_secret_key: ''
