---
- hosts: prod_app_servers
  become: yes
  tasks:
    - include_role: 
        name: web
    - include_role: 
        name: mysql
    - include_role:
        name: waytogo
    - include_role:
        name: aghs
