---
- hosts: all
  become: yes
  tasks:
    - import_role:
        name: usgo.devops_user
      tags:
        - usgo.devops_user

- hosts: lamp_servers
  become: yes
  tasks:
    - name: "Updating cache the test lamp servers if not updated in last hour"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - include_role: 
        name: web
    - import_role:
        name: mysql
      tags:
        - usgo.mysql
      vars:
        mysql_bind_address: '0.0.0.0'
    - include_role:
        name: usgo.wordpress
    - import_role:
        name: usgo.membership_manager
      tags:
        - usgo.membership_manager
    - import_role:
        name: usgo.agagd
      tags:
        - usgo.agagd 
    - include_role:
        name: cron.update.wordpress
