---
- hosts: frontend_servers
  tasks:
    - name: Append the docker group to the usgo_devops user
      ansible.builtin.user:
        name: usgo_devops
        groups: docker
      tags:
        - usgo.containers
    - import_role:
        name: usgo.containers
      tags:
        - usgo.containers
    - import_role:
        name: usgo.containers.nginx
      tags:
        - usgo.containers
        - usgo.containers.agagd
    - import_role:
        name: usgo.containers.agagd
      tags:
        - usgo.containers
        - usgo.containers.agagd

- hosts: lamp_servers
  tasks:
    - name: "Updating cache the test lamp servers if not updated in last hour"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - import_role:
        name: web
      tags:
        - usgo.web
    - import_role:
        name: mysql
      tags:
        - usgo.mysql
      vars:
        mysql_bind_address: '0.0.0.0'
    - import_role:
        name: usgo.drupal
      tags:
        - usgo.drupal
    - import_role:
        name: usgo.wordpress
      tags:
        - usgo.wordpress
    - import_role:
        name: usgo.membership_manager
      tags:
        - usgo.membership_manager
    - import_role:
        name: usgo.agagd
      tags:
        - usgo.agagd
    - import_role:
        name: cron.update.wordpress
      tags:
        - usgo.cron.update.wordpress
