---
- hosts: lamp_servers
  become: yes
  tasks:
    - import_role: 
        name: web
      tags:
        - usgo.web
    - import_role: 
        name: mysql
      tags:
        - usgo.mysql
    - import_role:
        name: waytogo
      tags:
        - usgo.waytogo
    - import_role:
        name: aghs
      tags:
        - usgo.aghs
    - import_role:
        name: collective_access
      tags:
        - usgo.collective_access
