---
- hosts: lamp_servers
  become: yes
  tasks:
    - name: "Updating cache the test lamp servers if not updated in last hour"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - import_role:
        name: web
      tags:
        - usgo.web
    - import_role:
        name: mysql
      tags:
        - usgo.mysql
      vars:
        mysql_bind_address: '0.0.0.0'
    - import_role:
        name: usgo.drupal
      tags:
        - usgo.drupal
    - import_role:
        name: usgo.wordpress
      tags:
        - usgo.wordpress
    - import_role:
        name: usgo.membership_manager
      tags:
        - usgo.membership
    - include_role:
        name: cron.update.wordpress

- hosts: database_servers
  become: yes
  tasks:
    - import_role:
        name: mysql
      vars:
        mysql_bind_address: '0.0.0.0'
      tags:
        - usgo.mysql
    - import_role:
        name: weareinteractive.ufw
      vars:
        ufw_rules:
          - rule: allow
            name: OpenSSH
          - rule: allow
            from_ip: '192.168.220.231'
            to_port: 3306
          - rule: allow
            from_ip: '192.168.141.105'
            to_port: 3306
    - import_role:
        name: usgo.backupmanager
      tags:
        - usgo.backupmanager
