---
- name: Archive the Existing Installation of EJournal Wordpress
  archive:
    path: "{{ usgo_www_root }}/news"
    dest: "{{ usgos_org_www_archives_dir }}/{{ ejournal_website_archive_filename }}"
  when: ejounal_website_archive_regex_found.matched < 1
