---
- name: Check if the Kabocha Theme Exists
  stat:
    path: "{{ wordpress_kabocha_theme_dir }}"
  register: kabocha_theme

- name: Check if wp-salts.php exists
  stat:
    path: "{{ wordpress_root }}/wp-salts.php"
  register: wp_salts

- name: Check if the Old EJournal is Archived
  find:
    paths: "{{ usgos_org_www_archives_dir }}"
    patterns: 'ejournal_website_*.bac.tar.gz'
  register: ejounal_website_archive_regex_found
