---
- name: Install PHP Requirements for USGO's Wordpress
  package:
    name: "{{ item }}"
  with_items: "{{ wordpress_php_packages }}"

- name: Download and Unarchive the Latest Wordpress
  unarchive:
    src: 'https://wordpress.org/latest.tar.gz'
    dest: "{{ wordpress_root }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
    keep_newer: yes
    extra_opts: [--strip-components=1]

- name: Add .htaccess to The Wordpress Install
  copy:
    src: .htaccess
    dest: "{{ wordpress_root }}/.htaccess"
    owner: root
    group: www-data
    mode: '0655'

- name: Add wp-config.php to the Wordpress install
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_root }}/wp-config.php"
    owner: root
    group: www-data
    mode: '0650'
