---
- name: Create the nginx-proxy docker container
  community.general.docker_container:
    name: nginx-proxy
    state: started
    recreate: yes
    restart_policy: always
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:rw

- name: Create the nginx vhost directory on host
  file:
    path: /etc/nginx/vhost.d
    owner: root
    group: root
    mode: '0644'
    recurse: yes

- name: Add templates for nginx vhosts to host
  template:
    src: "containers-{{ item.hostname }}.j2"
    dest: "/etc/nginx/vhost.d/{{ item.hostname }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ nginx_proxy_container_hosts }}"
  when:
    - nginx_proxy_container_hosts_provided

- name: Create the nginx-proxy docker container
  community.general.docker_container:
    name: nginx-proxy-companion
    state: started
    recreate: yes
    restart_policy: always
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    env:
      DEFAULT_EMAIL: "{{ usgo_nginx_certbot_email }}"
