---
- name: Create a directory for the nginx-proxy docker-compose files
  ansible.builtin.file:
    path: "{{ usgo_docker_compose_nginx_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create a directory for the apps docker-compose files
  ansible.builtin.file:
    path: "{{ usgo_docker_compose_apps_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add the configuration for the nignx-proxy
  ansible.builtin.file:
    src: 'docker-compose-nginx.yaml.j2'
    dest: "{{ usgo_docker_compose_nginx_directory }}/docker-compose-nginx.yaml"
    owner: root
    group: root
    mode: '0755'

- name: Deploy the nginx-proxy with letsencrypt
  docker_compose:
    project_src: "{{ usgo_docker_compose_nginx_directory }}"
    files:
      - 'docker-compose-nginx.yaml.j2'
