---
- name: Create the /root/.aws Directory
  ansible.builtin.file:
    path: /root/.aws
    state: directory
    mode: '0755'
  when: aws_root_credentials

- name: Create a /root/.aws/credentials
  ansible.builtin.template:
    src: credentials.j2
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: '0755'
  when: aws_root_credentials

- name: Create a /root/.aws/config
  ansible.builtin.template:
    src: config.j2
    dest: /root/.aws/config
    owner: root
    group: root
    mode: '0755'
  when: aws_root_credentials

- name: Create the docker systemd service override directory
  ansible.builtin.file:
    path: "{{ docker_systemd_directory }}"
    state: directory
    mode: '0755'
  when: not aws_root_credentials

- name: Create a aws configuration override for the systemd docker service
  ansible.builtin.template:
    src: aws_credentials.conf.j2
    dest: "{{ docker_systemd_directory }}/aws-credentials.conf"
    owner: root
    group: root
    mode: '0755'
  when: not aws_root_credentials
  notify:
    - restart docker

- name: Set the docker configuration for docker logging to awslogs
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart docker
