---
certbot_admin_email: webmaster@usgo.org

# Github Access Token
usgo_github_access_token: "{{ vault_github_access_token }}"

# Drupal Database Configuration
usgo_drupal_base_url: 'https://www.usgo.org'
usgo_drupal_database_host: "{{ vault_drupal_database_host }}"
usgo_drupal_database_name: "{{ vault_drupal_database_name }}"
usgo_drupal_database_prefix: "{{ vault_drupal_database_prefix }}"
usgo_drupal_database_user: "{{ vault_drupal_database_user }}"
usgo_drupal_database_pass: "{{ vault_drupal_database_pass }}"
usgo_drupal_salt: "{{ vault_drupal_salt }}"

# Additional Drupal Settings
usgo_cookie_domain: 'www.usgo.org'

# Drupal Production Version for usgo.org
usgo_drupal_version: '7.82'

# Drupal Production Modules for usgo.org
usgo_drupal_modules:
  - { name: 'advanced_help', version: '7.x-1.6', installed: True }
  - { name: 'calendar', version: '7.x-3.6', installed: True }
  - { name: 'captcha', version: '7.x-1.7', installed: True }
  - { name: 'cdn', version: '7.x-2.10', installed: True }
  - { name: 'ctools', version: '7.x-1.19', installed: True }
  - { name: 'date', version: '7.x-2.11', installed: True }
  - { name: 'devel', version: '7.x-1.6', installed: True }
  - { name: 'diff', version: '7.x-3.4', installed: True }
  - { name: 'drafty', version: '7.x-1.0-rc1', installed: True }
  - { name: 'entity', version: '7.x-1.9', installed: True }
  - { name: 'features', version: '7.x-2.13', installed: True }
  - { name: 'feeds', version: '7.x-2.0-beta5', installed: True }
  - { name: 'file_entity', version: '7.x-1.x-dev', installed: True }
  - { name: 'find_content', version: '7.x-1.7', installed: True }
  - { name: 'google_analytics', version: '7.x-2.6', installed: True }
  - { name: 'insert', version: '7.x-1.4', installed: True }
  - { name: 'job_scheduler', version: '7.x-2.0', installed: True }
  - { name: 'link', version: '7.x-1.9', installed: True }
  - { name: 'markdown', version: '7.x-1.6', installed: True }
  # - { name: 'markdown_abbr', version: '', installed: True }
  - { name: 'media', version: '7.x-2.0-unstable1', installed: True }
  - { name: 'menu_block', version: '7.x-2.8', installed: True }
  - { name: 'module_filter', version: '7.x-2.2', installed: True }
  - { name: 'panels', version: '7.x-3.10', installed: True } # Unused Module
  - { name: 'pathauto', version: '7.x-1.3', installed: True }
  - { name: 'recaptcha', version: '7.x-2.3', installed: True }
  - { name: 'redirect', version: '7.x-1.0-rc4', installed: True }
  - { name: 'rules', version: '7.x-2.12', installed: True }
  - { name: 'token', version: '7.x-1.8', installed: True }
  - { name: 'variable', version: '7.x-2.5', installed: True }
  - { name: 'video', version: '7.x-1.0-alpha2', installed: True }
  - { name: 'views', version: '7.x-3.24', installed: True }
  - { name: 'workbench', version: '7.x-1.2', installed: True }
  - { name: 'workbench_moderation', version: '7.x-3.0', installed: True }
  - { name: 'node_view_permissions', version: '7.x-1.6', installed: True }

# Current Production Membership Manager Version
usgo_membership_manager_version: '2021.05.03'

## Membership Manager Environment
mm_admin_debug_mode: 'false'
mm_frontend_debug_mode: 'false'
mm_scheduler_enabled: true
mm_admin_sitepath: "/mm/"
mm_frontend_sitepath: "/members/"
mm_site_url: 'https://www.usgo.org'
mm_contact_email: 'database@usgo.org'
mm_error_email: 'webmaster@usgo.org'
mm_db_host: "{{ vault_mm_db_host }}"
mm_db_name: "{{ vault_mm_db_name }}"
mm_db_user: "{{ vault_mm_db_user }}"
mm_db_pass: "{{ vault_mm_db_pass }}"

## Membership Manager PayPal Environment
mm_paypal_pay_url: 'https://www.paypal.com/cgi-bin/webscr'
mm_paypal_pdt_id:  "{{ vault_mm_paypal_pdt_id }}"
mm_paypal_business_id:  "{{ vault_mm_paypal_business_id }}"

# Wordpress Database Configurations
wordpress_database_host: "{{ vault_wordpress_database_host }}"
wordpress_database_name: "{{ vault_wordpress_database_name }}"
wordpress_database_user: "{{ vault_wordpress_database_user }}"
wordpress_database_pass: "{{ vault_wordpress_database_pass }}"
wordpress_table_prefix: "{{ vault_wordpress_table_prefix }}"

# Wordpress Plugins and Themes
wordpress_plugins:
  - name: add-to-any
  - name: advanced-excerpt
  - name: akismet
  - name: amazon-polly
  - name: broken-link-checker
  - name: gallery-plugin
  - name: glift-go-game
  - name: maintenance-mode
  - name: photo-gallery
  - name: social-networks-auto-poster-facebook-twitter-g
  - name: nextgen-gallery

vhost:
  - servername: usgo.org
    serveralias: www.usgo.org
    serveradmin: webmaster@usgo.org
    documentroot: /var/www/usgo.org
    include_extra_config: false
    extra_params: |
          RewriteEngine on
          RewriteCond %{SERVER_NAME} =usgo.org
          RewriteRule ^ https://www.%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent] 
          RewriteCond %{SERVER_NAME} =www.usgo.org
          RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
vhost_ssl:
  - servername: usgo.org
    serveralias: www.usgo.org
    serveradmin: webmaster@usgo.org
    ssl_domains: [ usgo.org, www.usgo.org ]
    documentroot: /var/www/usgo.org
    include_extra_config: true
    extra_params: |
          RewriteEngine on
          RewriteCond %{SERVER_NAME} =usgo.org
          RewriteRule ^ https://www.%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent] 
