---
- name: Create a Directory for the AGAGD Application
  file:
    path: "{{ agagd_root_directory }}/agagd_app"
    owner: root
    group: www-data
    state: directory
    mode: '0655'

- name: Download AGAGD Application from Github
  unarchive:
    src: "https://api.github.com/repos/usgo/agagd/tarball/master"
    dest: "{{ agagd_root_directory }}/agagd_app"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify: restart apache
