---
- name: Create a Directory for the AGAGD Application
  file:
    path: "{{ agagd_root_directory }}/agagd_app"
    owner: root
    group: www-data
    state: directory
    mode: '0655'

- name: Download AGAGD Application from Github
  unarchive:
    src: "https://api.github.com/repos/usgo/agagd/tarball/{{ agagd_version }}"
    dest: "{{ agagd_root_directory }}/agagd_app"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
    exclude:
      - 'agagd/agagd/settings/local_settings.py'
    extra_opts: [--strip-components=1]
  notify: restart apache
  register: agagd_download

- name: Add local_settings.py to the AGAGD Install
  template:
    src: local_settings.py.j2
    dest: "{{ agagd_root_directory }}/agagd_app/agagd/agagd/settings/local_settings.py"
    owner: root
    group: www-data
    mode: '0650'
