---
- name: Make the directory for way to go
  file:
    path: /var/www/wtg.usgo.org
    state: directory
    mode: '0755'

- name: Unarchive and Download the Way to Go Application
  unarchive:
    src: https://gitlab.com/way-to-go/way-to-go.gitlab.io/-/jobs/artifacts/master/download?job=pages
    dest: /var/www/wtg.usgo.org
    remote_src: yes
    owner: root
    group: www-data
    mode: 0755
