---
usgo_nginx_certbot_email: webmaster@usgo.org

## Google Analytics Configuration for the AGAGD
usgo_agagd_google_analytics_id: "{{ vault_agagd_frontend_google_analytics_id }}"

## Container Configuration for the AGAGD
usgo_agagd_min_containers: 4
usgo_container_agagd_version: '2021.11.1'
usgo_container_agagd_allowed_hosts: 'agagd.usgo.org'
usgo_container_agagd_db_host: "{{ vault_agagd_backend_db_host }}"
usgo_container_agagd_db_port: '3306'
usgo_container_agagd_db_name: "{{ vault_agagd_db_name }}"
usgo_container_agagd_db_user: agagd_ro_frontend_usr
usgo_container_agagd_db_password: "{{ vault_agagd_frontend_db_user_password }}"
usgo_container_agagd_secret_key: "{{ vault_agagd_frontend_secret_key }}"

## PHPMyAdmin Container Configuration
usgo_container_phpmyadmin_virtual_host: 'p.a.usgo.org'

## PHP MyAdmin Hosts Configuration
## Notes: Hosts are comma seperated i.e., host1,host2,etc
usgo_container_phpmyadmin_hosts: '192.168.133.43,192.168.192.90'
usgo_container_phpmyadmin_verboses: 'Main,Test'
