---
usgo_nginx_certbot_email: webmaster@usgo.org
usgo_container_agagd_version: 'latest'
usgo_container_agagd_virtual_host: 'b.agagd.usgo.org'
usgo_container_agagd_letsencrypt_host: 'b.agagd.usgo.org'
usgo_container_agagd_db_host: "{{ vault_agagd_backend_db_host }}"
usgo_container_agagd_db_port: '3306'
usgo_container_agagd_db_name: "{{ vault_agagd_db_name }}"
usgo_container_agagd_db_user: agagd_ro_frontend_usr
usgo_container_agagd_db_password: "{{ vault_agagd_frontend_db_user_password }}"
usgo_container_agagd_secret_key: "{{ vault_agagd_frontend_secret_key }}
