---
- name: Ensure mysql is mysqld for our custom configurations in /etc/mysql/conf.d/mysql.cnf
  lineinfile:
    path: /etc/mysql/conf.d/mysql.cnf
    regexp: '^\[mysql\]$'
    line: '[mysqld]'
    backrefs: yes
  notify:
    - restart mysql server

- name: Add our custom configurations are in /etc/mysql/conf.d/mysql.cnf
  lineinfile:
    path: /etc/mysql/conf.d/mysql.cnf
    regexp: "^sql_mode = "
    line: "sql_mode = \"{{ sql_mode }}\""
    state: present
  notify:
    - restart mysql server
