---
agagd_root_directory: "/var/www/agagd.usgo.org"
agagd_app_directory: "{{ agagd_root_directory }}/agagd_app"
agagd_requirements_txt: "{{ agagd_app_directory }}/requirements.txt"
agagd_virtenv_directory: "{{ agagd_root_directory }}/agagd_python_virtenv"
agagd_version: "master"
