---
- name: Create Drupal Install Dir
  file:
    path: "{{ usgo_drupal_dir }}"
    owner: root
    group: www-data
    mode: 0655
    state: directory

- name: Get Latest Drupal 7 Version
  unarchive:
    src: "https://ftp.drupal.org/files/projects/drupal-{{ usgo_drupal_version }}.tar.gz"
    dest: "{{ usgo_drupal_dir }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify: drush clear-cache

- name: Copy a the settings.php for Drupal 7 Version
  ansible.builtin.template:
    src: default.settings.php.j2
    dest: "{{ usgo_drupal_default_sites_dir }}/settings.php" 
    owner: root
    group: www-data
    mode: 0640

- name: Get the JSON Response from Github's API for USGO's Custom Drupal Modules
  uri:
    url: "https://api.github.com/repos/usgo/usgo_drupal_custom_modules?access_token={{ usgo_github_access_token }}"
    return_content: true
  register: usgos_custom_modules_json_response

- name: Create Custom and Community Directories
  file:
    path: "{{ usgo_drupal_modules_dir }}/{{ item }}"
    owner: root
    group: www-data
    mode: 0655
    recurse: yes
    state: directory
  with_items: ['custom', 'community']

- name: Download USGO's Custom Drupal Modules
  unarchive:
    src: "{{ usgos_custom_modules_json_response.json.url }}/tarball/master?access_token={{ usgo_github_access_token }}"
    dest: "{{ usgo_drupal_modules_dir }}/custom"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify: drush clear-cache

- name: Get Drupal Modules
  unarchive: 
    src: "https://ftp.drupal.org/files/projects/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ usgo_drupal_modules_dir }}/community"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
  with_items: "{{ usgo_drupal_modules }}"
  when: item.installed == True
  notify: drush clear-cache

- name: Create a Symbolic Link for the Kabocha Theme
  ansible.builtin.file:
    src: "{{ usgo_drupal_current_theme_location }}"
    dest: "{{ usgo_drupal_themes_dir }}/kabocha"
    owner: root
    group: www-data
    mode: '0655'
    state: link

- name: Create a Symbolic Link for the Files Directory
  ansible.builtin.file:
    src: "{{ usgo_drupal_current_files_location }}"
    dest: "{{ usgo_drupal_files_link_path }}"
    owner: root
    group: www-data
    mode: '0655'
    state: link
