---
- name: Get the JSON Response from Github's API for USGO's Custom Drupal Modules
  uri:
    src: "https://api.github.com/?access_token={{ usgo_github_token }}"
    return_content: true
  register: usgos_custom_modules_json_response

- name: Download USGO's Custom Drupal Modules
  unarchive:
    src: "{{ usgos_custom_modules_json_response.json.tarball_url }}?access_token={{ usgo_github_token }}"
    dest: "{{ usgo_drupal_dir }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes

- name: Get Drupal Modules
  unarchive: 
    src: "https://ftp.drupal.org/files/projects/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ usgo_drupal_modules_dir }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
  with_items: "{{ usgo_drupal_modules }}"
  when: item.installed == True

- name: Get Latest Drupal 7 Version
  unarchive:
    src: "https://ftp.drupal.org/files/projects/drupal-{{ usgo_drupal_version }}.tar.gz"
    dest: "{{ usgo_drupal_dir }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
