---
- name: Get USGO's Custom Modules
  git:
    src: git@github.com:usgo/usgo_drupal_custom_modules.git
    dest: "/tmp/custom_drupal_modules"
    depth: 1
    version: 'master'
  become: no

- name: Get Drupal Modules
  unarchive: 
    src: "https://ftp.drupal.org/files/projects/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ usgo_drupal_dir }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes
  with_items: "{{ usgo_drupal_modules }}"
  when: item.installed == True

- name: Get Latest Drupal 7 Version
  unarchive:
    src: "https://ftp.drupal.org/files/projects/drupal-{{ usgo_drupal_version }}.tar.gz"
    dest: "{{ usgo_drupal_dir }}"
    owner: root
    group: www-data
    mode: '0655'
    remote_src: yes

- name: Install Custom Modules
  synchronize:
    src: "/tmp/custom_drupal_modules/{{ item.name }}"
    dest: "{{ usgo_drupal_modules_dir }}/{{ item.name }}"
    owner: no
    group: no
    mode: pull
    rsync_opts:
      - '--chown=www-data:www-data'
      - '--chmod=D0755'  
  with_items: "{{ usgo_custom_drupal_modules }}" 

- name: Drop the Temp Directory for USGO's Custom Drupal Modules
  file:
    path: '/tmp/custom_drupal_modules'
    state: absent
