---
certbot_admin_email: webmaster@usgo.org
agagd_db_user: agagd_db_ro_usr 
agagd_db_name: "{{ vault_agagd_db_name }}"
agagd_db_user_password: "{{ vault_agagd_db_user_password }}"
agagd_secret_key: "{{ vault_agagd_secret_key }}"
agagd_google_analytics_tracking_id: "{{ vault_agagd_google_analytics_tracking_id }}"

# Current Production AGAGD Version
# - Date: August 31, 2020
agagd_version: '2020.08.31-alpha.1'

## Membership Manager Environment
mm_admin_debug_mode: 'false'
mm_frontend_debug_mode: 'false'
mm_scheduler_enabled: true
mm_admin_sitepath: "/mm/"
mm_frontend_sitepath: "/members/"
mm_site_url: 'https://www.usgo.org'
mm_contact_email: 'database@usgo.org'
mm_error_email: 'webmaster@usgo.org'
mm_db_host: "{{ vault_mm_db_host }}"
mm_db_name: "{{ vault_mm_db_name }}"
mm_db_user: "{{ vault_mm_db_user }}"
mm_db_pass: "{{ vault_mm_db_pass }}"

## Membership Manager PayPal Environment
mm_paypal_pay_url: 'https://www.paypal.com/cgi-bin/webscr'
mm_paypal_pdt_id:  "{{ vault_mm_paypal_pdt_id }}"
mm_paypal_business_id:  "{{ vault_mm_paypal_business_id }}"

# Wordpress Database Configurations
wordpress_database_host: "{{ vault_wordpress_database_host }}"
wordpress_database_name: "{{ vault_wordpress_database_name }}"
wordpress_database_user: "{{ vault_wordpress_database_user }}"
wordpress_database_pass: "{{ vault_wordpress_database_pass }}"
wordpress_table_prefix: "{{ vault_wordpress_table_prefix }}"

vhost:
  - servername: usgo.org
    serveralias: www.usgo.org
    serveradmin: webmaster@usgo.org
    documentroot: /var/www/usgo.org
    include_extra_config: false
    extra_params: |
          RewriteEngine on
          RewriteCond %{SERVER_NAME} =usgo.org
          RewriteRule ^ https://www.%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent] 
          RewriteCond %{SERVER_NAME} =www.usgo.org
          RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
  - servername: agagd.usgo.org
    serveradmin: webmaster@usgo.org
    documentroot: /var/www/agagd.usgo.org
    include_extra_config: false
    extra_params: |
          RewriteEngine on
          RewriteCond %{SERVER_NAME} =agagd.usgo.org
          RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
vhost_ssl:
  - servername: usgo.org
    serveralias: www.usgo.org
    serveradmin: webmaster@usgo.org
    ssl_domains: [ usgo.org, www.usgo.org ]
    documentroot: /var/www/usgo.org
    include_extra_config: true
    extra_params: |
          RewriteEngine on
          RewriteCond %{SERVER_NAME} =usgo.org
          RewriteRule ^ https://www.%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent] 
  - servername: agagd.usgo.org
    serveradmin: webmaster@usgo.org
    ssl_domains: [ agagd.usgo.org ]
    documentroot: /var/www/agagd.usgo.org
    include_extra_config: true
    outside_extra_params: |
          WSGIPythonPath /var/www/agagd.usgo.org/agagd_app/agagd:/var/www/agagd.usgo.org/agagd_python_virtenv/lib/python2.7/site-packages
