---
- name: Make the extra configuration directory
  file:
    path: "/etc/apache2/usgo_extra_confs"
    state: directory
    owner: root
    group: root

- name: Copy extra configuration files for vhosts
  template:
    src: "{{ item.servername }}.extra.conf.j2"
    dest: "/etc/apache2/usgo_extra_confs/{{ item.servername }}.extra.conf"
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart apache
  with_items: "{{ vhost }}"

- name: Import a basic apache2 virtual host template
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.servername }}.conf"
  notify:
    - restart apache
  with_items: "{{ vhost }}"

- name: Add vhost symlink in sites-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ item.servername }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.servername }}.conf"
    state: link
  notify: 
    - restart apache
  with_items: "{{ vhost }}"
  when: vhost is defined

