---
- name: Create the archives file location
  file:
    path: "{{ bm_repository_root }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install BackupManager
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
    - backup-manager
    - gcc
    - g++
    - make

- name: Install App::cpanminus
  command: "cpan install App::cpanminus"

- name: Install CPANM
  community.general.cpanm:
    name: "{{ item }}"
  with_items:
   - Log::Log4perl
   - Moose
   - DateTime
   - LWP::Protocol::https
   - Net::Amazon::S3

- name: Add the config template file backup-manager.conf
  template:
    src: "backup-manager.conf.j2"
    dest: "/etc/backup-manager.conf"
    owner: root
    group: root
    mode: '0650'

- name: Add the config template file for backup-manager-mysql.conf
  ansible.builtin.copy:
    src: "etc/backup-manager-mysql.conf"
    dest: "/etc/backup-manager-mysql.conf"
    owner: root
    group: root
    mode: '0650'

- name: Add a General Crontab for Backup Manager
  ansible.builtin.cron:
    name: "General Crontab for Backup Manager"
    hour: "0"
    job: "/usr/sbin/backup-manager"

- name: Add a Crontab for Backup Manager MySQL
  ansible.builtin.cron:
    name: "Crontab for Backup Manager MySQL"
    hour: "2"
    job: "/usr/sbin/backup-manager -c /etc/backup-manager-mysql.conf"

- name: Add a General Crontab for Backup Manager Uploads
  ansible.builtin.cron:
    name: "General Crontab for Backup Manager Uploads"
    hour: "3"
    job: "/usr/sbin/backup-manager -u"

