---
- name: Create the archives file location
  file:
    path: "{{ bm_repository_root }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install BackupManager
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
    - backup-manager
    - gcc
    - g++
    - make

- name: Install App::cpanminus
  command: "cpan install App::cpanminus"

- name: Install CPANM
  community.general.cpanm:
    name: "{{ item }}"
  with_items:
   - Log::Log4perl
   - Moose
   - DateTime
   - Net::Amazon::S3

- name: Add the config template file
  template:
    src: "backup-manager.conf.j2"
    dest: "/etc/backup-manager.conf"
    owner: root
    group: root
    mode: '0650'
